In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import scipy.stats as ss
from scipy.stats import chi2_contingency

In [3]:
data = pd.read_csv("application_record.csv")

In [4]:
data.shape

(438557, 18)

In [5]:
data = data.sample(5000)

In [6]:
data.shape

(5000, 18)

In [7]:
data.head()

,ID,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,DAYS_BIRTH,DAYS_EMPLOYED,FLAG_MOBIL,FLAG_WORK_PHONE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS
319465,6264439,F,N,Y,0,202500.0,Pensioner,Secondary / secondary special,Civil marriage,House / apartment,-22549,365243,1,0,0,0,NaN,2.0
4896,5024370,F,N,N,0,112500.0,Pensioner,Secondary / secondary special,Married,House / apartment,-23598,365243,1,0,0,0,NaN,2.0
28916,5706579,F,N,Y,1,135000.0,Working,Secondary / secondary special,Single / not married,House / apartment,-14524,-1222,1,0,0,1,NaN,2.0
345363,6800280,M,Y,Y,0,405000.0,Commercial associate,Higher education,Married,House / apartment,-13728,-1644,1,0,0,0,Managers,2.0
186452,5860917,F,N,Y,0,270000.0,Pensioner,Secondary / secondary special,Separated,House / apartment,-23335,365243,1,0,0,0,NaN,1.0

In [8]:
data = data.drop('DAYS_BIRTH', axis=1)

In [9]:
data = data.drop('DAYS_EMPLOYED', axis=1)

In [10]:
data.head()

,ID,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,FLAG_MOBIL,FLAG_WORK_PHONE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS
319465,6264439,F,N,Y,0,202500.0,Pensioner,Secondary / secondary special,Civil marriage,House / apartment,1,0,0,0,NaN,2.0
4896,5024370,F,N,N,0,112500.0,Pensioner,Secondary / secondary special,Married,House / apartment,1,0,0,0,NaN,2.0
28916,5706579,F,N,Y,1,135000.0,Working,Secondary / secondary special,Single / not married,House / apartment,1,0,0,1,NaN,2.0
345363,6800280,M,Y,Y,0,405000.0,Commercial associate,Higher education,Married,House / apartment,1,0,0,0,Managers,2.0
186452,5860917,F,N,Y,0,270000.0,Pensioner,Secondary / secondary special,Separated,House / apartment,1,0,0,0,NaN,1.0

In [11]:
data.dtypes

ID                       int64
CODE_GENDER             object
FLAG_OWN_CAR            object
FLAG_OWN_REALTY         object
CNT_CHILDREN             int64
AMT_INCOME_TOTAL       float64
NAME_INCOME_TYPE        object
NAME_EDUCATION_TYPE     object
NAME_FAMILY_STATUS      object
NAME_HOUSING_TYPE       object
FLAG_MOBIL               int64
FLAG_WORK_PHONE          int64
FLAG_PHONE               int64
FLAG_EMAIL               int64
OCCUPATION_TYPE         object
CNT_FAM_MEMBERS        float64
dtype: object

In [12]:
data['FLAG_MOBIL'] = data.FLAG_MOBIL.astype(object)
data['FLAG_WORK_PHONE'] = data.FLAG_WORK_PHONE.astype(object)
data['FLAG_PHONE'] = data.FLAG_PHONE.astype(object)
data['FLAG_EMAIL'] = data.FLAG_EMAIL.astype(object)

In [13]:
data.dtypes

ID                       int64
CODE_GENDER             object
FLAG_OWN_CAR            object
FLAG_OWN_REALTY         object
CNT_CHILDREN             int64
AMT_INCOME_TOTAL       float64
NAME_INCOME_TYPE        object
NAME_EDUCATION_TYPE     object
NAME_FAMILY_STATUS      object
NAME_HOUSING_TYPE       object
FLAG_MOBIL              object
FLAG_WORK_PHONE         object
FLAG_PHONE              object
FLAG_EMAIL              object
OCCUPATION_TYPE         object
CNT_FAM_MEMBERS        float64
dtype: object

In [14]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5000 entries, 319465 to 338847
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   5000 non-null   int64
 1   CODE_GENDER          5000 non-null   object
 2   FLAG_OWN_CAR         5000 non-null   object
 3   FLAG_OWN_REALTY      5000 non-null   object
 4   CNT_CHILDREN         5000 non-null   int64
 5   AMT_INCOME_TOTAL     5000 non-null   float64
 6   NAME_INCOME_TYPE     5000 non-null   object
 7   NAME_EDUCATION_TYPE  5000 non-null   object
 8   NAME_FAMILY_STATUS   5000 non-null   object
 9   NAME_HOUSING_TYPE    5000 non-null   object
 10  FLAG_MOBIL           5000 non-null   object
 11  FLAG_WORK_PHONE      5000 non-null   object
 12  FLAG_PHONE           5000 non-null   object
 13  FLAG_EMAIL           5000 non-null   object
 14  OCCUPATION_TYPE      3480 non-null   object
 15  CNT_FAM_MEMBERS      5000 non-null   float64
dtypes: float64(2), int64(2), object(12)
memory usage: 664.1+ KB

In [15]:
# Analisis univariado
# calcula la media 
data['AMT_INCOME_TOTAL'].mean()

np.float64(187413.462)

In [16]:
#calcular la mediana 
data['AMT_INCOME_TOTAL'].median()

157500.0

In [17]:
#calcular los cuartiles 
data['AMT_INCOME_TOTAL'].quantile()

np.float64(157500.0)

In [18]:
#cacular moda
data['AMT_INCOME_TOTAL'].mode()

0    135000.0
Name: AMT_INCOME_TOTAL, dtype: float64

In [19]:
#calcular los cuartiles 
data['AMT_INCOME_TOTAL'].quantile([0])

0.0    27000.0
Name: AMT_INCOME_TOTAL, dtype: float64

In [20]:
#calcular los cuartiles 
data['AMT_INCOME_TOTAL'].quantile([1])

1.0    3150000.0
Name: AMT_INCOME_TOTAL, dtype: float64

In [22]:
#calcular los cuartiles 
data['AMT_INCOME_TOTAL'].quantile([0.25])

0.25    126000.0
Name: AMT_INCOME_TOTAL, dtype: float64

In [23]:
#calcular los cuartiles 
data['AMT_INCOME_TOTAL'].quantile([0.45])

0.45    157500.0
Name: AMT_INCOME_TOTAL, dtype: float64

In [24]:
#calcula decil
data['AMT_INCOME_TOTAL'].quantile([0.10])

0.1    90000.0
Name: AMT_INCOME_TOTAL, dtype: float64

In [25]:
#rango 
data['AMT_INCOME_TOTAL'].min()

27000.0

In [26]:
data['AMT_INCOME_TOTAL'].max()

3150000.0

In [27]:
data['AMT_INCOME_TOTAL'].max()-data['AMT_INCOME_TOTAL'].min()

3123000.0

In [28]:
#Rango
data['CNT_CHILDREN'].min()

0

In [30]:
data['CNT_CHILDREN'].var() # varianza

0.5195048609721686

In [31]:
data['CNT_CHILDREN'].std() #desviancion estandar

0.7207668561831687

In [32]:
data['AMT_INCOME_TOTAL'].std()

108881.30518342044

In [33]:
data['AMT_INCOME_TOTAL'].std(ddof=0) # poblacional

108870.41650844114

# tarea: investigar varianza, desviacion estandar, cuartiles, deciles, poblacional, coeficiente de variacion,muestral coefeciente de curtosis  coeficiente de asimetria , shapiro, Prueba de normalidad

In [33]:
data['AMT_INCOME_TOTAL'].std(ddof=0) # poblacional

108870.41650844114

In [34]:
data['AMT_INCOME_TOTAL'].std(ddof=1) #muestral

108881.30518342044

In [36]:
#coeficiente de variacion AMT_INCOME_TOTAL
data['AMT_INCOME_TOTAL'].std(ddof=0)/data['AMT_INCOME_TOTAL'].mean()

np.float64(0.5809103324095317)

In [37]:
##coeficiente de variacion  CNT_CHILDREN
data['CNT_CHILDREN'].std(ddof=0)/data['CNT_CHILDREN'].mean()

np.float64(1.656008216666718)

In [38]:
# coeficiente de asimetria 
ss.skew(data['AMT_INCOME_TOTAL'])

np.float64(6.329855435746971)

In [39]:
# coefeciente de curtosis 
ss.kurtosis(data['AMT_INCOME_TOTAL'])

np.float64(122.90695670639097)

In [41]:
# resumen 
data['AMT_INCOME_TOTAL'].describe()

count    5.000000e+03
mean     1.874135e+05
std      1.088813e+05
min      2.700000e+04
25%      1.260000e+05
50%      1.575000e+05
75%      2.250000e+05
max      3.150000e+06
Name: AMT_INCOME_TOTAL, dtype: float64

In [48]:
# Prueba de normalidad 
# como el pvalue < 5%, se rechaza HO  SI AL 95% de confianza se concluye que los ingresos anuales 
# de los clientes no se aproximan a la normalidad 
ss.shapiro(data.AMT_INCOME_TOTAL)

ShapiroResult(statistic=np.float64(0.716486860893194), pvalue=np.float64(2.315375728892843e-68))

In [49]:
ss.normaltest(data.AMT_INCOME_TOTAL)

NormaltestResult(statistic=np.float64(6268.148902155819), pvalue=np.float64(0.0))

In [51]:
ss.shapiro(data.CNT_CHILDREN)

ShapiroResult(statistic=np.float64(0.6400945908200788), pvalue=np.float64(3.3475939924039264e-73))

In [52]:
ss.shapiro(data.CNT_FAM_MEMBERS)

ShapiroResult(statistic=np.float64(0.8371098515886655), pvalue=np.float64(8.956760744734274e-58))